import { useState, useEffect } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import api from '../api/client';
import { BookOpen, CheckCircle, Circle, Lock, Unlock, Calendar, Briefcase, ChevronRight, ChevronDown, Loader2 } from 'lucide-react';

const LearningPathPage = () => {
    const [field, setField] = useState('');
    const queryClient = useQueryClient();

    // Fetch existing path
    const { data: learningPath, isLoading: isLoadingPath } = useQuery({
        queryKey: ['learningPath'],
        queryFn: async () => {
            try {
                const res = await api.get('/learning-paths');
                return res.data;
            } catch (err) {
                return null; // No path found
            }
        },
        retry: false
    });

    // Generate new path mutation
    const generatePathMutation = useMutation({
        mutationFn: async (field: string) => {
            const res = await api.post('/learning-paths', { field });
            return res.data;
        },
        onSuccess: (data) => {
            queryClient.setQueryData(['learningPath'], data);
        }
    });

    const handleGenerate = (e: React.FormEvent) => {
        e.preventDefault();
        if (field.trim()) {
            generatePathMutation.mutate(field);
        }
    };

    if (isLoadingPath) {
        return <div className="flex justify-center items-center h-screen">Loading...</div>;
    }

    return (
        <div className="min-h-screen bg-neutral-softGray p-8">
            <div className="max-w-6xl mx-auto">
                <h1 className="text-3xl font-heading font-bold text-neutral-charcoal mb-2">AI Learning Path</h1>
                <p className="text-gray-600 mb-8">Personalized curriculum, skill tree, and projects generated by AI.</p>

                {!learningPath && !generatePathMutation.isPending && (
                    <div className="bg-white p-8 rounded-2xl shadow-sm max-w-2xl mx-auto text-center">
                        <BookOpen className="w-16 h-16 text-primary mx-auto mb-4" />
                        <h2 className="text-2xl font-bold mb-4">Start Your Journey</h2>
                        <p className="text-gray-600 mb-6">Enter a field you want to master (e.g., "Full Stack Development", "Data Science") and we'll generate a complete roadmap for you.</p>
                        <form onSubmit={handleGenerate} className="flex gap-4">
                            <input
                                type="text"
                                value={field}
                                onChange={(e) => setField(e.target.value)}
                                placeholder="Enter a field..."
                                className="flex-1 px-4 py-3 rounded-xl border border-gray-300 focus:ring-2 focus:ring-primary focus:border-transparent outline-none"
                            />
                            <button
                                type="submit"
                                disabled={!field.trim()}
                                className="bg-primary text-white px-6 py-3 rounded-xl font-bold hover:bg-opacity-90 disabled:opacity-50"
                            >
                                Generate Path
                            </button>
                        </form>
                    </div>
                )}

                {generatePathMutation.isPending && (
                    <div className="text-center py-20">
                        <Loader2 className="w-12 h-12 text-primary animate-spin mx-auto mb-4" />
                        <h3 className="text-xl font-bold text-gray-700">Generating your personalized path...</h3>
                        <p className="text-gray-500">This may take up to 30 seconds.</p>
                    </div>
                )}

                {learningPath && (
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                        {/* Left Column: Weekly Plan */}
                        <div className="lg:col-span-2 space-y-6">
                            <div className="bg-white p-6 rounded-2xl shadow-sm">
                                <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
                                    <Calendar className="w-5 h-5 text-blue-600" />
                                    Weekly Study Plan
                                </h2>
                                <div className="space-y-6">
                                    {learningPath.weeklyPlan.map((week: any) => (
                                        <div key={week.weekNumber} className="border border-gray-100 rounded-xl p-4 bg-gray-50">
                                            <h3 className="font-bold text-lg text-gray-800 mb-3">Week {week.weekNumber}: {week.topic}</h3>
                                            <div className="space-y-3">
                                                {week.tasks.map((task: any) => (
                                                    <div key={task.id} className="flex items-start gap-3 bg-white p-3 rounded-lg border border-gray-200">
                                                        {task.isCompleted ? (
                                                            <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
                                                        ) : (
                                                            <Circle className="w-5 h-5 text-gray-300 mt-0.5 flex-shrink-0" />
                                                        )}
                                                        <div>
                                                            <p className={`font-medium ${task.isCompleted ? 'text-gray-500 line-through' : 'text-gray-800'}`}>{task.title}</p>
                                                            <p className="text-sm text-gray-500 mt-1">{task.description}</p>
                                                        </div>
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>

                        {/* Right Column: Skill Tree & Projects */}
                        <div className="space-y-6">
                            {/* Skill Tree */}
                            <div className="bg-white p-6 rounded-2xl shadow-sm">
                                <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
                                    <Unlock className="w-5 h-5 text-purple-600" />
                                    Skill Tree
                                </h2>
                                <div className="relative pl-4 border-l-2 border-gray-200 space-y-6">
                                    {learningPath.skillTree.map((node: any) => (
                                        <div key={node.id} className="relative">
                                            <div className={`absolute -left-[21px] top-1 w-4 h-4 rounded-full border-2 ${node.isCompleted ? 'bg-green-500 border-green-500' : node.isUnlocked ? 'bg-white border-blue-500' : 'bg-gray-200 border-gray-300'}`} />
                                            <div className={`p-3 rounded-lg border ${node.isCompleted ? 'bg-green-50 border-green-200' : node.isUnlocked ? 'bg-blue-50 border-blue-200' : 'bg-gray-50 border-gray-200'}`}>
                                                <h4 className={`font-bold ${node.isCompleted ? 'text-green-800' : node.isUnlocked ? 'text-blue-800' : 'text-gray-500'}`}>{node.label}</h4>
                                                {node.children.length > 0 && (
                                                    <p className="text-xs text-gray-500 mt-1">Unlocks: {node.children.join(', ')}</p>
                                                )}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>

                            {/* Projects */}
                            <div className="bg-white p-6 rounded-2xl shadow-sm">
                                <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
                                    <Briefcase className="w-5 h-5 text-orange-600" />
                                    Projects
                                </h2>
                                <div className="space-y-4">
                                    {learningPath.projects.map((project: any) => (
                                        <div key={project.id} className="border border-gray-200 rounded-xl p-4">
                                            <div className="flex justify-between items-start mb-2">
                                                <h4 className="font-bold text-gray-800">{project.title}</h4>
                                                {project.isCompleted && <span className="bg-green-100 text-green-700 text-xs px-2 py-1 rounded-full font-bold">Done</span>}
                                            </div>
                                            <p className="text-sm text-gray-600 mb-3">{project.description}</p>
                                            <div className="flex items-center gap-2 text-xs text-orange-600 font-medium bg-orange-50 px-3 py-1.5 rounded-lg w-fit">
                                                <Calendar className="w-3 h-3" />
                                                Due: {new Date(project.deadline).toLocaleDateString()}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default LearningPathPage;
