import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import api from '../api/client';
import { BookOpen, CheckCircle, Circle, Unlock, Calendar, Briefcase, Loader2, ChevronLeft, ChevronRight, RefreshCw, X, ExternalLink, PlayCircle, FileText } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

const LearningPathPage = () => {
    const [field, setField] = useState('');
    const [currentWeekIndex, setCurrentWeekIndex] = useState(0);
    const [selectedTopic, setSelectedTopic] = useState<string | null>(null);
    const [resources, setResources] = useState<any>(null);
    const queryClient = useQueryClient();

    // Fetch existing path
    const { data: learningPath, isLoading: isLoadingPath } = useQuery({
        queryKey: ['learningPath'],
        queryFn: async () => {
            try {
                const res = await api.get('/learning-paths');
                return res.data;
            } catch (err) {
                return null; // No path found
            }
        },
        retry: false
    });

    // Generate new path mutation
    const generatePathMutation = useMutation({
        mutationFn: async (field: string) => {
            const res = await api.post('/learning-paths', { field });
            return res.data;
        },
        onSuccess: (data) => {
            queryClient.setQueryData(['learningPath'], data);
            setCurrentWeekIndex(0);
        }
    });

    // Delete path mutation
    const deletePathMutation = useMutation({
        mutationFn: async () => {
            await api.delete('/learning-paths');
        },
        onSuccess: () => {
            queryClient.setQueryData(['learningPath'], null);
            setField('');
        }
    });

    // Fetch resources mutation
    const fetchResourcesMutation = useMutation({
        mutationFn: async (topic: string) => {
            const res = await api.post('/learning-paths/resources', { topic });
            return res.data;
        },
        onSuccess: (data) => {
            setResources(data);
        }
    });

    const handleGenerate = (e: React.FormEvent) => {
        e.preventDefault();
        if (field.trim()) {
            generatePathMutation.mutate(field);
        }
    };

    const handleTopicClick = (topic: string) => {
        setSelectedTopic(topic);
        setResources(null);
        fetchResourcesMutation.mutate(topic);
    };

    const closeResourceModal = () => {
        setSelectedTopic(null);
        setResources(null);
    };

    if (isLoadingPath) {
        return <div className="flex justify-center items-center h-screen"><Loader2 className="w-8 h-8 animate-spin text-primary" /></div>;
    }

    const currentWeek = learningPath?.weeklyPlan[currentWeekIndex];

    return (
        <div className="min-h-screen bg-neutral-softGray p-8 relative">
            <div className="max-w-6xl mx-auto">
                <div className="flex justify-between items-center mb-2">
                    <h1 className="text-3xl font-heading font-bold text-neutral-charcoal">AI Learning Path</h1>
                    {learningPath && (
                        <button
                            onClick={() => {
                                if (window.confirm('Are you sure you want to reset your learning path? This cannot be undone.')) {
                                    deletePathMutation.mutate();
                                }
                            }}
                            className="flex items-center gap-2 text-red-500 hover:text-red-700 font-medium px-4 py-2 rounded-lg hover:bg-red-50 transition-colors"
                        >
                            <RefreshCw className="w-4 h-4" />
                            Reset Path
                        </button>
                    )}
                </div>
                <p className="text-gray-600 mb-8">Personalized curriculum, skill tree, and projects generated by AI.</p>

                {!learningPath && !generatePathMutation.isPending && (
                    <div className="bg-white p-8 rounded-2xl shadow-sm max-w-2xl mx-auto text-center">
                        <BookOpen className="w-16 h-16 text-primary mx-auto mb-4" />
                        <h2 className="text-2xl font-bold mb-4">Start Your Journey</h2>
                        <p className="text-gray-600 mb-6">Enter a field you want to master (e.g., "Full Stack Development", "Data Science") and we'll generate a complete roadmap for you.</p>
                        <form onSubmit={handleGenerate} className="flex gap-4">
                            <input
                                type="text"
                                value={field}
                                onChange={(e) => setField(e.target.value)}
                                placeholder="Enter a field..."
                                className="flex-1 px-4 py-3 rounded-xl border border-gray-300 focus:ring-2 focus:ring-primary focus:border-transparent outline-none"
                            />
                            <button
                                type="submit"
                                disabled={!field.trim()}
                                className="bg-primary text-white px-6 py-3 rounded-xl font-bold hover:bg-opacity-90 disabled:opacity-50"
                            >
                                Generate Path
                            </button>
                        </form>
                    </div>
                )}

                {generatePathMutation.isPending && (
                    <div className="text-center py-20">
                        <Loader2 className="w-12 h-12 text-primary animate-spin mx-auto mb-4" />
                        <h3 className="text-xl font-bold text-gray-700">Generating your personalized path...</h3>
                        <p className="text-gray-500">This may take up to 30 seconds.</p>
                    </div>
                )}

                {learningPath && (
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                        {/* Left Column: Weekly Plan (Carousel) */}
                        <div className="lg:col-span-2 space-y-6">
                            <div className="bg-white p-6 rounded-2xl shadow-sm min-h-[500px] flex flex-col">
                                <div className="flex justify-between items-center mb-6">
                                    <h2 className="text-xl font-bold flex items-center gap-2">
                                        <Calendar className="w-5 h-5 text-blue-600" />
                                        Weekly Study Plan
                                    </h2>
                                    <div className="flex gap-2">
                                        <button
                                            onClick={() => setCurrentWeekIndex(prev => Math.max(0, prev - 1))}
                                            disabled={currentWeekIndex === 0}
                                            className="p-2 rounded-full hover:bg-gray-100 disabled:opacity-30 disabled:cursor-not-allowed"
                                        >
                                            <ChevronLeft className="w-5 h-5" />
                                        </button>
                                        <span className="font-medium text-gray-700 px-2">
                                            Week {currentWeekIndex + 1} of {learningPath.weeklyPlan.length}
                                        </span>
                                        <button
                                            onClick={() => setCurrentWeekIndex(prev => Math.min(learningPath.weeklyPlan.length - 1, prev + 1))}
                                            disabled={currentWeekIndex === learningPath.weeklyPlan.length - 1}
                                            className="p-2 rounded-full hover:bg-gray-100 disabled:opacity-30 disabled:cursor-not-allowed"
                                        >
                                            <ChevronRight className="w-5 h-5" />
                                        </button>
                                    </div>
                                </div>

                                <AnimatePresence mode="wait">
                                    <motion.div
                                        key={currentWeekIndex}
                                        initial={{ opacity: 0, x: 20 }}
                                        animate={{ opacity: 1, x: 0 }}
                                        exit={{ opacity: 0, x: -20 }}
                                        transition={{ duration: 0.2 }}
                                        className="flex-1"
                                    >
                                        <div className="border border-gray-100 rounded-xl p-6 bg-gray-50 h-full">
                                            <div className="flex items-center gap-3 mb-4">
                                                <h3 className="font-bold text-2xl text-gray-800">{currentWeek.topic}</h3>
                                                <button
                                                    onClick={() => handleTopicClick(currentWeek.topic)}
                                                    className="text-xs bg-blue-100 text-blue-700 px-3 py-1 rounded-full font-bold hover:bg-blue-200 transition-colors flex items-center gap-1"
                                                >
                                                    <BookOpen className="w-3 h-3" />
                                                    Learn More
                                                </button>
                                            </div>

                                            <div className="space-y-4">
                                                {currentWeek.tasks.map((task: any) => (
                                                    <div key={task.id} className="flex items-start gap-4 bg-white p-4 rounded-xl border border-gray-200 shadow-sm hover:shadow-md transition-shadow">
                                                        <button className="mt-1">
                                                            {task.isCompleted ? (
                                                                <CheckCircle className="w-6 h-6 text-green-500" />
                                                            ) : (
                                                                <Circle className="w-6 h-6 text-gray-300 hover:text-primary" />
                                                            )}
                                                        </button>
                                                        <div>
                                                            <p className={`font-bold text-lg ${task.isCompleted ? 'text-gray-500 line-through' : 'text-gray-800'}`}>{task.title}</p>
                                                            <p className="text-gray-600 mt-1">{task.description}</p>
                                                        </div>
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    </motion.div>
                                </AnimatePresence>
                            </div>
                        </div>

                        {/* Right Column: Skill Tree & Projects */}
                        <div className="space-y-6">
                            {/* Skill Tree */}
                            <div className="bg-white p-6 rounded-2xl shadow-sm">
                                <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
                                    <Unlock className="w-5 h-5 text-purple-600" />
                                    Skill Tree
                                </h2>
                                <div className="relative pl-4 border-l-2 border-gray-200 space-y-6 max-h-[300px] overflow-y-auto pr-2 custom-scrollbar">
                                    {learningPath.skillTree.map((node: any) => (
                                        <div key={node.id} className="relative">
                                            <div className={`absolute -left-[21px] top-1 w-4 h-4 rounded-full border-2 ${node.isCompleted ? 'bg-green-500 border-green-500' : node.isUnlocked ? 'bg-white border-blue-500' : 'bg-gray-200 border-gray-300'}`} />
                                            <div className={`p-3 rounded-lg border ${node.isCompleted ? 'bg-green-50 border-green-200' : node.isUnlocked ? 'bg-blue-50 border-blue-200' : 'bg-gray-50 border-gray-200'}`}>
                                                <h4 className={`font-bold ${node.isCompleted ? 'text-green-800' : node.isUnlocked ? 'text-blue-800' : 'text-gray-500'}`}>{node.label}</h4>
                                                {node.children.length > 0 && (
                                                    <p className="text-xs text-gray-500 mt-1">Unlocks: {node.children.join(', ')}</p>
                                                )}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>

                            {/* Projects */}
                            <div className="bg-white p-6 rounded-2xl shadow-sm">
                                <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
                                    <Briefcase className="w-5 h-5 text-orange-600" />
                                    Projects
                                </h2>
                                <div className="space-y-4">
                                    {learningPath.projects.map((project: any) => (
                                        <div key={project.id} className="border border-gray-200 rounded-xl p-4">
                                            <div className="flex justify-between items-start mb-2">
                                                <h4 className="font-bold text-gray-800">{project.title}</h4>
                                                {project.isCompleted && <span className="bg-green-100 text-green-700 text-xs px-2 py-1 rounded-full font-bold">Done</span>}
                                            </div>
                                            <p className="text-sm text-gray-600 mb-3">{project.description}</p>
                                            <div className="flex items-center gap-2 text-xs text-orange-600 font-medium bg-orange-50 px-3 py-1.5 rounded-lg w-fit">
                                                <Calendar className="w-3 h-3" />
                                                Due: {new Date(project.deadline).toLocaleDateString()}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                )}
            </div>

            {/* Resources Modal */}
            <AnimatePresence>
                {selectedTopic && (
                    <div className="fixed inset-0 bg-black/50 z-50 flex justify-end">
                        <motion.div
                            initial={{ x: '100%' }}
                            animate={{ x: 0 }}
                            exit={{ x: '100%' }}
                            transition={{ type: 'spring', damping: 25, stiffness: 200 }}
                            className="w-full max-w-md bg-white h-full shadow-2xl p-6 overflow-y-auto"
                        >
                            <div className="flex justify-between items-center mb-6">
                                <h3 className="text-xl font-bold text-gray-900">{selectedTopic}</h3>
                                <button onClick={closeResourceModal} className="p-2 hover:bg-gray-100 rounded-full">
                                    <X className="w-6 h-6 text-gray-500" />
                                </button>
                            </div>

                            {fetchResourcesMutation.isPending ? (
                                <div className="flex flex-col items-center justify-center py-20 text-gray-500">
                                    <Loader2 className="w-10 h-10 animate-spin text-primary mb-4" />
                                    <p>Curating resources for you...</p>
                                </div>
                            ) : resources ? (
                                <div className="space-y-6">
                                    <div className="bg-blue-50 p-4 rounded-xl border border-blue-100">
                                        <h4 className="font-bold text-blue-800 mb-2 flex items-center gap-2">
                                            <BookOpen className="w-4 h-4" />
                                            Concept Explanation
                                        </h4>
                                        <p className="text-blue-900 text-sm leading-relaxed">
                                            {resources.explanation}
                                        </p>
                                    </div>

                                    <div>
                                        <h4 className="font-bold text-gray-800 mb-4 flex items-center gap-2">
                                            <ExternalLink className="w-4 h-4" />
                                            Recommended Resources
                                        </h4>
                                        <div className="space-y-3">
                                            {resources.resources.map((res: any, idx: number) => (
                                                <a
                                                    key={idx}
                                                    href={res.url}
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                    className="block p-4 border border-gray-200 rounded-xl hover:border-primary hover:shadow-md transition-all group"
                                                >
                                                    <div className="flex items-start gap-3">
                                                        <div className="p-2 bg-gray-100 rounded-lg group-hover:bg-primary/10 transition-colors">
                                                            {res.type?.toLowerCase().includes('video') ? (
                                                                <PlayCircle className="w-5 h-5 text-gray-600 group-hover:text-primary" />
                                                            ) : (
                                                                <FileText className="w-5 h-5 text-gray-600 group-hover:text-primary" />
                                                            )}
                                                        </div>
                                                        <div>
                                                            <h5 className="font-bold text-gray-800 group-hover:text-primary transition-colors">{res.title}</h5>
                                                            <span className="text-xs text-gray-500 bg-gray-100 px-2 py-0.5 rounded mt-1 inline-block">
                                                                {res.type || 'Resource'}
                                                            </span>
                                                        </div>
                                                    </div>
                                                </a>
                                            ))}
                                        </div>
                                    </div>
                                </div>
                            ) : (
                                <div className="text-center text-red-500 py-10">
                                    Failed to load resources. Please try again.
                                </div>
                            )}
                        </motion.div>
                    </div>
                )}
            </AnimatePresence>
        </div>
    );
};

export default LearningPathPage;
